contact_links:
  - name: Questions (Stack Overflow)
    url: http://slack.keystonejs.com/
    about: Reach out to our Stack Overflow community.
  - name: Feature Requests (GitHub Discussions)
    url: https://github.com/keystonejs/keystone/discussions
    about: Discuss Keystone Next with us!
  - name: Chat (Slack)
    url: http://slack.keystonejs.com/
    about: Discuss Keystone Next with us!
