contact_links:
  - name: Question (Stack Overflow)
    url: http://slack.keystonejs.com/
    about: Reach out to our Stack Overflow community.
  - name: Feature request (GitHub Discussions)
    url: https://github.com/keystonejs/keystone/discussions
    about: Tell us about your ideas for Keystone Next.
  - name: Chat (Slack)
    url: http://slack.keystonejs.com/
    about: Get the latest announcements about Keystone Next and and chat with the community.
