contact_links:
  - name: Question or Feature Request (Slack)
    url: http://slack.keystonejs.com/
    about: Discuss or request a feature in Keystone Next.
  - name: Question (Stack Overflow)
    url: http://slack.keystonejs.com/
    about: Reach out to our Stack Overflow community.
